Repository cdklabs/construct-hub, pull requests merged in 2024-02, with the labels that each got.

#1382 chore(deps): upgrade dev dependencies
  package.json
  src/__tests__/__snapshots__/construct-hub.test.ts.snap
  src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap
  src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap
  yarn.lock
Labels: auto-approve

#1381 fix: Feed builder lambda times out
  docs/operator-runbook.md
  src/__tests__/__snapshots__/construct-hub.test.ts.snap
  src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap
  src/backend/feed-builder/index.ts
  src/construct-hub.ts
Labels: bug

#1383 chore(deps): upgrade dev dependencies
  package.json
  src/__tests__/__snapshots__/construct-hub.test.ts.snap
  src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap
  src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap
  yarn.lock
Labels: auto-approve

#1385 chore(deps): upgrade dev dependencies
  package.json
  src/__tests__/__snapshots__/construct-hub.test.ts.snap
  src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap
  src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap
  yarn.lock
Labels: auto-approve

#1386 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1387 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1389 chore: upgrade network ACL allow-lists
  resources/vpc-allow-lists/github.api-IPv4.txt
  resources/vpc-allow-lists/github.git-IPv4.txt
  resources/vpc-allow-lists/github.web-IPv4.txt
  src/__tests__/__snapshots__/_limited-internet-access.test.ts.snap
  src/__tests__/__snapshots__/construct-hub.test.ts.snap
Labels: auto-approve

#1390 fix: Remove .DS_Store file
  .DS_Store
  .gitignore
  .projenrc.ts
Labels: risk/low

#1391 chore(deps): upgrade dev dependencies
  .github/workflows/build.yml
  .github/workflows/pull-request-lint.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-cdklabs-projen-project-types-main.yml
  .github/workflows/upgrade-dev-deps-main.yml
  .github/workflows/upgrade-main.yml
  .projen/tasks.json
  API.md
  package.json
  src/__tests__/__snapshots__/construct-hub.test.ts.snap
  src/__tests__/backend/deny-list/__snapshots__/deny-list.test.ts.snap
  src/__tests__/backend/deny-list/integ/deny-list.integ.cdkout/TestDenyList.assets.json
  src/__tests__/backend/deny-list/integ/deny-list.integ.cdkout/TestDenyList.template.json
  src/__tests__/backend/license-list/__snapshots__/license-list.test.ts.snap
  src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap
  src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap
  src/__tests__/package-sources/__snapshots__/code-artifact.test.ts.snap
  src/spdx-license.ts
  yarn.lock
Labels: auto-approve
